# Generated by Django 3.2.10 on 2022-02-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ref_app", "0004_auto_20220206_1132"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompartmentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("date", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name="refrigeratormodel",
            old_name="doorname",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="ingredientsmodel",
            name="ref_door",
        ),
        migrations.RemoveField(
            model_name="refrigeratormodel",
            name="category",
        ),
        migrations.AddField(
            model_name="ingredientsmodel",
            name="compartment",
            field=models.ManyToManyField(to="ref_app.CompartmentModel"),
        ),
    ]
