# Generated by Django 3.2.10 on 2022-02-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ref_app', '0007_auto_20220209_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientsmodel',
            name='expiration_date',
            field=models.DateField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
