# Generated by Django 3.2.10 on 2022-02-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ref_app", "0008_ingredientsmodel_expiration_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="InfomationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("tixt", models.TextField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name="ingredientsmodel",
            name="expiration_date",
            field=models.DateField(),
        ),
    ]
