# Generated by Django 4.0.3 on 2022-03-15 13:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ref_app", "0018_ingredientshistory"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="IngredientsHistory",
            new_name="IngredientsHistoryModel",
        ),
    ]
