# Generated by Django 4.0.3 on 2022-03-16 13:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ref_app", "0020_ingredientshistorymodel_ingre"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ingredientshistorymodel",
            name="ingre_name",
        ),
    ]
