# Generated by Django 4.0.3 on 2022-03-20 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ref_app', '0021_remove_ingredientshistorymodel_ingre_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientshistorymodel',
            name='ingre',
        ),
        migrations.AddField(
            model_name='ingredientshistorymodel',
            name='ingre_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ref_app.ingredientsmodel', verbose_name='食材名'),
        ),
    ]
