# Generated by Django 4.0.3 on 2022-03-20 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ref_app', '0022_remove_ingredientshistorymodel_ingre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientshistorymodel',
            name='update_user',
        ),
    ]
