# Generated by Django 4.0.3 on 2022-04-02 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ref_app', '0029_alter_ingredientshistorymodel_ingre_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientshistorymodel',
            name='username',
            field=models.CharField(default='null', max_length=50, verbose_name='更新者'),
            preserve_default=False,
        ),
    ]
