# Generated by Django 4.0.3 on 2022-04-07 14:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("ref_app", "0031_ingredientshistorymodel_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ingredientsmodel",
            name="date",
        ),
        migrations.AddField(
            model_name="ingredientsmodel",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ingredientsmodel",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
