# Generated by Django 4.0.3 on 2022-04-30 11:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ref_app", "0034_infomationmodel_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SalesInfoModel",
        ),
    ]
